### ISSUE TITLE
Is it possible to connect to cloud services or externalhosts?

### ISSUE THREAD

**Issue by deck-hthai** [PHOENIX-MEDIA/magento2-helm#29]
I'm currently trying to set this up on EKS but my aim is to also use this with external services like RDS and AWS Opensearch, is it possible to add that functionality or is it all ready inside of the chart.yaml/values.yaml.

Would there be any downside to doing this? 

The main aim I'm looking for is to use the magento-php pods and leverage cloud services for high availability, and thank you again for creating the helm charts/images for this.

**Comment by phoenix-bjoern** [comment]
This is absolutely possible and there is already an [issue](https://github.com/PHOENIX-MEDIA/magento2-helm/issues/15) to add the documentation for that. So I'm happy to collaborate with you on this.

On a high level I see the following steps:
1. Create a dedicated `values_external_service.yaml` to configure all settings
2. Disable charts/services you want to replace by external services:
```
mariadb
  enabled: false
opensearch
  enabled: false
```
3. Create K8S Services for the external services:
```
extraObjects:
- apiVersion: v1
  kind: Service
  metadata:
    name: mysql
    namespace: my-magento-ns
  spec:
    type: ExternalName
    externalName: my.database.example.com
- apiVersion: v1
  kind: Service
  metadata:
    name: elasticsearch
    namespace: my-magento-ns
  spec:
    type: ExternalName
    externalName: my.opensearch.example.com
```
4. Set credentials in the [`secrets` section](https://github.com/PHOENIX-MEDIA/magento2-helm/blob/main/values.yaml#L941)

Would love to see your PR with an new section in the `README.md` describing the details and maybe also networking related settings.
